### ISSUE TITLE
Tagged CI builds are failing

### ISSUE THREAD

**Issue by revett** [CityOfZion/neo-local#37]
## Problem

Example: https://travis-ci.org/CityOfZion/neo-local/builds/409058230

CI builds on the master branch or a tag should ignore the `make check-version` check as that should apply to a feature branch.

See:

https://github.com/CityOfZion/neo-local/blob/fb455dbc9a50523ac49a13711324812e40d87507/scripts/travis.sh#L1-L12

**Comment by jeroenptrs** [comment]
@revett upon research I stumbled upon the fact that `$TRAVIS_BRANCH` is either empty or contains the tag name on tagged builds, which is why the build runs `make check-versions`.

**References:**
* https://github.com/Didstopia/PDFSharp/issues/34
* https://docs.travis-ci.com/user/environment-variables/#default-environment-variables

**Proposal:**
Use `$TRAVIS_TAG` instead

**Comment by anthdm** [comment]
Hello? Will this be merged soon? Or at least reviewed? @jeroenptrs you can add me as second reviewers to make this pass?
